site_name: Ishara Documentation
site_url: https://github.com/williamsryan/ishara
repo_url: https://github.com/williamsryan/ishara
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting_started.md
      - Installation: installation.md
  - Modules:
      - Test Case Generation: test_case_gen.md
      - Execution: execution.md
      - Analysis: analysis.md
  - Kernel:
      - Kernel Module: kernel.md
      - Makefile: makefile.md
  - Contributing: contributing.md
plugins:
  - search
  # - mkdocs-git-revision-date-plugin
markdown_extensions:
  - codehilite
  - admonition
  - toc

